services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: task_app
    network_mode: "host"
    environment:
      # Database Configuration
      SPRING_DATASOURCE_URL: jdbc:mysql://localhost:3306/task_management
      SPRING_DATASOURCE_USERNAME: your_username
      SPRING_DATASOURCE_PASSWORD: your_password
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      # Email Configuration for sending reports
      EMAIl_USERNAME: your_email
      EMAIL_PASSWORD: your_email_password

